package com.se.mapping;

// Generated Mar 21, 2015 7:24:01 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Patient generated by hbm2java
 */
public class Patient implements java.io.Serializable {

	private Integer id;
	public String name;
	public int age;
	private int sex;
	public String address;
	public String phoneNo;
	private Date storeDate;
	public Set visits = new HashSet(0);

	public Patient() {
	}

	public Patient(String name, int age, int sex, String address,
			String phoneNo, Date storeDate) {
		this.name = name;
		this.age = age;
		this.sex = sex;
		this.address = address;
		this.phoneNo = phoneNo;
		this.storeDate = storeDate;
	}

	public Patient(String name, int age, int sex, String address,
			String phoneNo, Date storeDate, Set visits) {
		this.name = name;
		this.age = age;
		this.sex = sex;
		this.address = address;
		this.phoneNo = phoneNo;
		this.storeDate = storeDate;
		this.visits = visits;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public int getSex() {
		return this.sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	public Date getStoreDate() {
		return this.storeDate;
	}

	public void setStoreDate(Date storeDate) {
		this.storeDate = storeDate;
	}

	public Set getVisits() {
		return this.visits;
	}

	public void setVisits(Set visits) {
		this.visits = visits;
	}

}
