package com.se.mapping;

// Generated Mar 21, 2015 7:24:01 PM by Hibernate Tools 3.6.0

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int id;
	private String userName;
	private String password;
	private Integer role;
	private Boolean notActive;

	public Users() {
	}

	public Users(int id) {
		this.id = id;
	}

	public Users(int id, String username, String password, Integer role,
			Boolean notActive) {
		this.id = id;
		this.userName = username;
		this.password = password;
		this.role = role;
		this.notActive = notActive;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String username) {
		this.userName = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getRole() {
		return this.role;
	}

	public void setRole(Integer role) {
		this.role = role;
	}

	public Boolean getNotActive() {
		return this.notActive;
	}

	public void setNotActive(Boolean notActive) {
		this.notActive = notActive;
	}

}
