package com.se.mapping;

// Generated Mar 21, 2015 7:24:01 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Visit generated by hbm2java
 */
public class Visit implements java.io.Serializable {

	private Integer id;
	private Patient patient;
	private String complaint;
	private String hpi;
	private String ph;
	private String ears;
	private String nose;
	private String pharynx;
	private String larynx;
	private String neckOtherareas;
	private String otherData;
	private String investigationDone;
	private String investigationRequest;
	private String treatment;
	private Date visitDate;

	private Set<Followup> followups = new HashSet<Followup>(0);

	public Visit() {
	}

	public Visit(Patient patient, String complaint, String hpi, String ph,
			String ears, String nose, String pharynx, String larynx,
			String neckOtherareas, String otherData, String investigationDone,
			String investigationRequest, String treatment) {
		this.patient = patient;
		this.complaint = complaint;
		this.hpi = hpi;
		this.ph = ph;
		this.ears = ears;
		this.nose = nose;
		this.pharynx = pharynx;
		this.larynx = larynx;
		this.neckOtherareas = neckOtherareas;
		this.otherData = otherData;
		this.investigationDone = investigationDone;
		this.investigationRequest = investigationRequest;
		this.treatment = treatment;
	}

	public Visit(Patient patient, String complaint, String hpi, String ph,
			String ears, String nose, String pharynx, String larynx,
			String neckOtherareas, String otherData, String investigationDone,
			String investigationRequest, String treatment, Set<Followup> followups) {
		this.patient = patient;
		this.complaint = complaint;
		this.hpi = hpi;
		this.ph = ph;
		this.ears = ears;
		this.nose = nose;
		this.pharynx = pharynx;
		this.larynx = larynx;
		this.neckOtherareas = neckOtherareas;
		this.otherData = otherData;
		this.investigationDone = investigationDone;
		this.investigationRequest = investigationRequest;
		this.treatment = treatment;
		this.followups = followups;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public String getComplaint() {
		return this.complaint;
	}

	public void setComplaint(String complaint) {
		this.complaint = complaint;
	}

	public String getHpi() {
		return this.hpi;
	}

	public void setHpi(String hpi) {
		this.hpi = hpi;
	}

	public String getPh() {
		return this.ph;
	}

	public void setPh(String ph) {
		this.ph = ph;
	}

	public String getEars() {
		return this.ears;
	}

	public void setEars(String ears) {
		this.ears = ears;
	}

	public String getNose() {
		return this.nose;
	}

	public void setNose(String nose) {
		this.nose = nose;
	}

	public String getPharynx() {
		return this.pharynx;
	}

	public void setPharynx(String pharynx) {
		this.pharynx = pharynx;
	}

	public String getLarynx() {
		return this.larynx;
	}

	public void setLarynx(String larynx) {
		this.larynx = larynx;
	}

	public String getNeckOtherareas() {
		return this.neckOtherareas;
	}

	public void setNeckOtherareas(String neckOtherareas) {
		this.neckOtherareas = neckOtherareas;
	}

	public String getOtherData() {
		return this.otherData;
	}

	public void setOtherData(String otherData) {
		this.otherData = otherData;
	}

	public String getInvestigationDone() {
		return this.investigationDone;
	}

	public void setInvestigationDone(String investigationDone) {
		this.investigationDone = investigationDone;
	}

	public String getInvestigationRequest() {
		return this.investigationRequest;
	}

	public void setInvestigationRequest(String investigationRequest) {
		this.investigationRequest = investigationRequest;
	}

	public String getTreatment() {
		return this.treatment;
	}

	public void setTreatment(String treatment) {
		this.treatment = treatment;
	}

	public Set<Followup> getFollowups() {
		return this.followups;
	}

	public void setFollowups(Set<Followup> followups) {
		this.followups = followups;
	}

	public Date getVisitDate() {
		return visitDate;
	}

	public void setVisitDate(Date visitDate) {
		this.visitDate = visitDate;
	}

}
